### ISSUE TITLE
The number of channels of depth map

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [fdp0525/G2LTex#17]
Hi, thanks a lot for your great work! I am trying to run this code on my own recording and encountered the same error mentioned in #16 with 
```bash
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor
```

I guess this is related to color space conversion in your library. I am wondering whether you enforce the 16bit depth to be saved in some specific shape, e.g. `[H, W, C]` which must be 3-dimensional even `C=1`?

Any suggestion will be appreciated! Thanks

**Comment by Xiaoming-Zhao** [comment]
For anyone who encountered similar issues, after trial and error, I find that we need to keep the file name with a two-digit number as `color_00.jpg` until `color_99.jpg`. Then we can use `color_100.jpg` etc hereafter. A similar strategy should be applied to `depth_00.png` and `color_00.cam`.

**Comment by yanqingan** [comment]
> For anyone who encountered similar issues, after trial and error, I find that we need to keep the file name with a two-digit number as `color_00.jpg` until `color_99.jpg`. Then we can use `color_100.jpg` etc hereafter. A similar strategy should be applied to `depth_00.png` and `color_00.cam`.

Thanks for the try and good suggestion.
