### ISSUE TITLE
Could not load image header

### ISSUE THREAD

**Issue by byj200493** [fdp0525/G2LTex#21]
When running G2LTex, it said that it could not load image header.
![ice_screenshot_20210607-105801](https://user-images.githubusercontent.com/46087057/120953346-5a9dd800-c77f-11eb-9b2f-dce4403bceaa.png)
How can I fix it?

**Comment by chihyu-chen** [comment]
Hi @byj200493,
I am encountering the same issue. Do you happen to remember how you solved it?
Thank you so much in advance!
