### ISSUE TITLE
compile the code

### ISSUE THREAD

**Issue by hjwdzh** [fdp0525/G2LTex#6]
Is it possible for you provide the additional makefile or cmake configuration for compilation?

**Comment by yanqingan** [comment]
There is no need to compile the project. It has already been compiled.

**Comment by hjwdzh** [comment]
Yes. I just figured it out. Thanks for the quick response!

I think it may be a good idea to also provide libcholmod/opencv dependencies, otherwise users need to carefully set the dependencies in the right way.

**Comment by yanqingan** [comment]
Thank you for the suggestion. We will work on it. It is sure that the additionally required 2.x opencv dependency is inconvenient. I usually use the temporary command “export LD_LIBRARY_PATH” to link a different local opencv version.
